--liquibase formatted sql

--changeset felipe:1
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

--rollback DROP EXTENSION IF EXISTS "pgcrypto";

--changeset felipe:2
CREATE TABLE IF NOT EXISTS "LOJA"(
    "ID" UUID NOT NULL,
    CONSTRAINT "PK_LOJA" PRIMARY KEY ("ID")
);

--rollback DROP TABLE IF EXISTS "LOJA";

--changeset felipe:3
CREATE TABLE IF NOT EXISTS "CATEGORIA"(
    "ID" UUID NOT NULL,
    "NOME" VARCHAR(200) NOT NULL,
    "DESCRICAO" VARCHAR(500) NULL,
    "ID_LOJA" UUID NOT NULL,
    CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CATEGORIA_LOJA" FOREIGN KEY ("ID_LOJA") REFERENCES "LOJA"("ID")
);

--rollback DROP TABLE IF EXISTS "CATEGORIA";

--changeset felipe:4
CREATE TABLE IF NOT EXISTS "PRODUTO"(
    "ID" UUID NOT NULL,
    "NOME" VARCHAR(200) NOT NULL,
    "DESCRICAO" VARCHAR(2000) NULL,
    "VALOR" NUMERIC(8,2) NOT NULL,
    "MINIATURA" BYTEA NOT NULL,
    "ID_CATEGORIA" UUID NULL,
    CONSTRAINT "PK_PRODUTO" PRIMARY KEY("ID"),
    CONSTRAINT "FK_PRODUTO_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "CATEGORIA"("ID")
)

--rollback DROP TABLE IF EXISTS "PRODUTO";

--changeset felipe:5
CREATE INDEX "IDX_PRODUTO_CATEGORIA" ON "PRODUTO"("ID_CATEGORIA");

CREATE INDEX "IDX_CATEGORIA_LOJA" ON "CATEGORIA"("ID_LOJA");

CREATE UNIQUE INDEX "IDX_CATEGORIA_NOME" ON "CATEGORIA"("NOME");

--rollback DROP INDEX IF EXISTS "IDX_PRODUTO_CATEGORIA"; DROP INDEX IF EXISTS "IDX_CATEGORIA_LOJA"; DROP INDEX IF EXISTS "IDX_CATEGORIA_NOME";